### ISSUE TITLE
VST3 fails to scan on REAPER Linux

### ISSUE THREAD

**Issue by DaforLynx** [prof-spock/FluidSynthPlugin#22]
Using the latest release of the native Linux .so file on Arch Linux on the latest version of REAPER. Plugin fails to scan, though REAPER interestingly lists it as a .vst3 file.

**Comment by prof-spock** [comment]
Hello DaforLynx,

have you noticed that the latest versions of FluidSynthPlugin now **require** a package installation of FluidSynth for Linux? Since the so/vst3-file needs other libraries (which it cannot find in your configuration) this might be the reason for the reported behavior.

For ArchLinux you have to install FluidSynth with
`pacman -S fluidsynth`

I have just tested the plugin with Reaper 7.2.8 and the stable package fluidsynth 2.3.4 on Ubuntu 24.04 without any problems.

Best regards,
Prof. Spock

**Comment by DaforLynx** [comment]
Ah, that seems to work. Thanks for the help.
