### ISSUE TITLE
new GUI feature build: incorrect filetype filter in Linux

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#8]
In the Linux build of the new GUI feature version, when browsing for a SoundFont, the filter is set as `*.sf2,*.sf3`. This results in no files showing. Replacing the comma with a space fixes the problem and shows both .sf2 and .sf3 files, e.g. `*.sf2 *.sf3`.

My OS: KDE neon User Edition 6.0 with KDE Plasma 6

**Comment by prof-spock** [comment]
Hello mrbumpy409,

you wrote:
> the filter is set as *.sf2,*.sf3. This results in no files showing.

That leaves me completely puzzled: I have checked all three platforms (Windows 10, MacOSX10.15 and Ubuntu 22.04) and the selection works fine for those (see attached screenshots).
Maybe - since I am using the generic file selection dialog - the filtering syntax may depend on the file manager?

On the other hand the [official JUCE documentation](https://docs.juce.com/master/classFileChooser.html#afd55c3c97c97e23a0b18818156dfb71c)  says:
> **filePatternsAllowed**    a  set of file patterns to specify which files can be selected - each  pattern should be separated by a comma or semi-colon, e.g. "*" or  "*.jpg;*.gif"

Could you kindly try whether a semicolon works on your system? Anyway, I'll find out and keep you informed.

Best regards,
Prof. Spock
![Windows-FileSelectionDialog](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/520723e1-b7d1-4c74-adaf-f7731e4aa99b)
**Windows**

![MacOSX-FileSelectionDialog](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/015c2569-5e37-4a9c-802e-a7ee551ef00b)
**MacOSX**

![Ubuntu-FileSelectionDialog](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/e9e1b2f6-a1e5-4c50-98a0-4d5eb5965b13)
**Ubuntu**

**Comment by mrbumpy409** [comment]
Strange. I'll admit I don't know a lot about how this is all supposed to work, and the bug could be in JUCE or the KDE file picker. Anyway, here is what I get with a comma (and also same result with a semicolon):
![image](https://github.com/prof-spock/FluidSynthPlugin/assets/6825789/24ba694e-3f13-4eea-831e-5f51b585b16b)

And here it is with a space instead:
![image](https://github.com/prof-spock/FluidSynthPlugin/assets/6825789/127dd016-6aa2-4777-a1ee-4489ab5648e7)

Interestingly, the GNOME file picker from your Ubuntu screenshot shows a space in the file filter.

**Comment by prof-spock** [comment]
Yep, I'll try whether space works for all platforms even though the JUCE documentation suggests otherwise...

**Comment by mrbumpy409** [comment]
Hey, using a semicolon in the source code instead of a comma results in success on my system. With the source code as `*.sf2;*.sf3`, when the file picker comes up, it shows the file types separated by a space (`*.sf2 *.sf3`), and everything works.

**Comment by prof-spock** [comment]
Hello mrbumby409,

I've revised the filtering according to your suggestion.

Best regards,
Prof. Spock

**Comment by mrbumpy409** [comment]
Everything is working great now. Thanks!

**Comment by prof-spock** [comment]
part of release 0.7.0, see [release notes](https://github.com/prof-spock/FluidSynthPlugin/releases/tag/v0.7.0)
